version: "3"

volumes:
  mysql:


services:

  my-mysql:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: rootpaswd
        MYSQL_DATABASE: cbox_db
        MYSQL_USER: cbox
        MYSQL_PASSWORD: cboxpass
    ports: 
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql


  cbox-app:
    image: olegnew/cbox-manager:v1.4
    ports:
      - 8080:8080
    network_mode: host
    depends_on:
      - my-mysql


